--- 
cn:thunderlord: cn
eu:anub'arak: eu
kr:sartharion: kr
eu:die silberne hand: eu
cn:garithos: cn
us:aerie peak: us
eu:suramar: eu
cn:mal'ganis: cn
cn:swiftwind: cn
cn:spirestone: cn
us:zangarmarsh: us
tw:howling fjord: tw
us:eonar: us
cn:khadgar: cn
eu:neptulon: eu
us:vashj: us
cn:sutarn: cn
cn:theramore: cn
eu:terenas: eu
eu:burning steppes: eu
tw:menethil: tw
cn:turalyon: cn
us:the forgotten coast: us
cn:maiev shadowsong: cn
us:eldre'thalas: us
us:lightbringer: us
cn:kel'thuzad: cn
cn:frostreaver crown: cn
us:uldum: us
us:winterhoof: us
eu:sinstralis: eu
eu:genjuros: eu
eu:perenolde: eu
tw:hellscream: tw
cn:circle of blood: cn
cn:varimathras: cn
kr:karazhan: kr
cn:nozdormu: cn
cn:antonidas: cn
cn:freewind: cn
eu:archimonde: eu
us:lightninghoof: us
cn:staghelm: cn
cn:stormreaver: cn
us:maelstrom: us
us:burning blade: us
cn:twisting nether: cn
us:moonrunner: us
eu:quel'thalas: eu
eu:eredar: eu
cn:zalazane: cn
eu:burning blade: eu
eu:malorne: eu
us:deathwing: us
kr:al'ar: kr
us:sentinels: us
eu:arathor: eu
"eu:\xD0\x9F\xD0\xBE\xD0\xB4\xD0\xB7\xD0\xB5\xD0\xBC\xD1\x8C\xD0\xB5": eu
eu:elune: eu
cn:kaleidoscope star: cn
cn:lordaeron: cn
us:zul'jin: us
eu:der abyssische rat: eu
eu:rexxar: eu
cn:hydraxis: cn
eu:al'akir: eu
eu:kilrogg: eu
cn:dreamwalker: cn
us:zuluhed: us
eu:kult der verdammten: eu
cn:drakkisath: cn
us:dreadmaul: us
eu:frostmourne: eu
us:major league gaming: us
kr:rexxar: kr
us:korgath: us
cn:sunwell: cn
kr:aegwynn: kr
tw:zealot blade: tw
cn:thrall: cn
us:arena tournament 1: us
us:agamaggan: us
tw:skywall: tw
cn:whitemane: cn
us:arena tournament 2: us
eu:ravencrest: eu
cn:vancleef: cn
cn:menethil: cn
us:arena tournament 3: us
cn:bladespire: cn
cn:dath'remar: cn
tw:chillwind point: tw
cn:nighthaven: cn
"eu:\xD0\x90\xD0\xB7\xD1\x83\xD1\x80\xD0\xB5\xD0\xB3\xD0\xBE\xD1\x81": eu
cn:crushridge: cn
cn:feralas: cn
eu:stonemaul: eu
us:arena tournament 4: us
eu:forscherliga: eu
cn:the great sea: cn
cn:dun modr: cn
cn:mosh'ogg: cn
eu:die nachtwache: eu
cn:tirisfal glades: cn
cn:khaz'goroth: cn
eu:stormscale: eu
us:dawnbringer: us
us:kil'jaeden: us
eu:les clairvoyants: eu
cn:detheroc: cn
us:muradin: us
us:nordrassil: us
cn:ravenholdt: cn
us:feathermoon: us
us:the scryers: us
us:hyjal: us
cn:the veiled sea: cn
cn:abyssal maw: cn
cn:river pride: cn
us:nagrand: us
cn:drakkari: cn
cn:silvermoon: cn
kr:malygos: kr
cn:gul'dan: cn
cn:maelstrom: cn
eu:laughing skull: eu
cn:dreadmist peak: cn
cn:ysondre: cn
"eu:chants \xC3\xA9ternels": eu
kr:blackmoore: kr
cn:red cloud mesa: cn
cn:deathwing: cn
cn:blackwing lair: cn
cn:destromath: cn
us:anub'arak: us
eu:twisting nether: eu
eu:chamber of aspects: eu
eu:epitech: eu
kr:cenarius: kr
eu:shattrath: eu
tw:arygos: tw
eu:moonglade: eu
eu:thrall: eu
cn:tyr's hand: cn
cn:daggerspine: cn
eu:tarren mill: eu
cn:coilfang: cn
tw:crystalpine stinger: tw
eu:aman'thul: eu
tw:deathwing: tw
kr:stormrage: kr
eu:ambossar: eu
cn:zuluhed: cn
us:ragnaros: us
eu:nazjatar: eu
eu:terokkar: eu
kr:eonar: kr
cn:tempest keep: cn
eu:stormreaver: eu
cn:dreadmaul: cn
cn:gothik: cn
eu:kor'gall: eu
tw:tichondrius: tw
cn:the master's glaive: cn
cn:amani: cn
eu:dalvengyr: eu
eu:vek'nilash: eu
cn:ysera: cn
us:boulderfist: us
cn:midnight scythe: cn
cn:amnennar: cn
us:fenris: us
cn:zealot blade: cn
cn:theradras: cn
us:gurubashi: us
us:lothar: us
us:perenolde: us
cn:agamaggan: cn
cn:molten core: cn
us:dentarg: us
cn:the arcatraz: cn
cn:shrine of the dormant flame: cn
eu:darksorrow: eu
eu:balnazzar: eu
us:warsong: us
us:sargeras: us
cn:magtheridon: cn
cn:thunder bluff: cn
us:blade's edge: us
eu:runetotem: eu
cn:the golden plains: cn
us:nesingwary: us
cn:al'ar: cn
us:demon soul: us
eu:spinebreaker: eu
eu:los errantes: eu
cn:felmyst: cn
cn:azgalor: cn
us:baelgun: us
eu:tyrande: eu
us:madoran: us
us:blackwater raiders: us
cn:gordunni: cn
cn:akama: cn
tw:dragonmaw: tw
cn:ashenvale: cn
cn:dor'danil: cn
cn:neptulon: cn
eu:culte de la rive noire: eu
cn:the underbog: cn
tw:shadowmoon: tw
us:farstriders: us
cn:guardian blade: cn
cn:anub'arak: cn
cn:quel'thalas: cn
tw:silverwing hold: tw
cn:murmur: cn
eu:anetheron: eu
cn:anachronos: cn
cn:brann: cn
cn:blue dragonflight: cn
cn:stormscale: cn
us:earthen ring: us
eu:area 52: eu
cn:thaurissan: cn
eu:durotan: eu
"eu:confr\xC3\xA9rie du thorium": eu
tw:firetree: tw
cn:anvilmar: cn
eu:sylvanas: eu
eu:dethecus: eu
us:eitrigg: us
eu:nefarian: eu
cn:sinestra: cn
cn:nazjatar: cn
us:frostmourne: us
eu:die aldor: eu
eu:das syndikat: eu
us:stonemaul: us
us:archimonde: us
cn:sunstrider: cn
cn:falathim: cn
cn:duskwood: cn
cn:gurubashi: cn
eu:skullcrusher: eu
eu:chromaggus: eu
cn:perenolde: cn
eu:steamwheedle cartel: eu
cn:un'goro: cn
kr:burning legion: kr
eu:kirin tor: eu
eu:haomarush: eu
cn:therazane: cn
cn:warsong: cn
cn:bloodscalp: cn
eu:krasus: eu
eu:stormrage: eu
cn:demon soul: cn
eu:daggerspine: eu
us:thunderlord: us
eu:eu arena pass csbg: eu
"eu:\xD0\xA7\xD0\xB5\xD1\x80\xD0\xBD\xD1\x8B\xD0\xB9 \xD0\xA8\xD1\x80\xD0\xB0\xD0\xBC": eu
eu:defias brotherhood: eu
cn:bleeding hollow: cn
cn:wing of the whelping: cn
cn:madoran: cn
us:maiev: us
us:ghostlands: us
us:scarlet crusade: us
cn:demon fall canyon: cn
us:laughing skull: us
cn:blanchard: cn
eu:mannoroth: eu
eu:khaz modan: eu
cn:crystalpine stinger: cn
eu:the venture co: eu
us:ysera: us
cn:zul'aman: cn
cn:arthas: cn
us:quel'dorei: us
us:aman'thul: us
cn:tichondrius: cn
eu:vol'jin: eu
cn:thermaplugg: cn
cn:stonetalon peak: cn
eu:molten core: eu
tw:arena tournament 1: tw
cn:kilrogg: cn
tw:icecrown: tw
cn:claw of the shadowmancer: cn
tw:arena tournament 2: tw
us:dalvengyr: us
eu:magtheridon: eu
tw:arena tournament 3: tw
eu:teldrassil: eu
us:velen: us
cn:blackmoore: cn
cn:medivh: cn
eu:twilight's hammer: eu
eu:karazhan: eu
cn:gorgonnash: cn
eu:blackrock: eu
cn:red dragonflight: cn
us:coliseum 1: us
cn:astranaar: cn
us:stormreaver: us
us:balnazzar: us
cn:isillien: cn
cn:skullcrusher: cn
eu:kel'thuzad: eu
eu:dalaran: eu
us:saurfang: us
eu:c'thun: eu
eu:illidan: eu
cn:tarren mill: cn
eu:eonar: eu
kr:coliseum 1: kr
us:sen'jin: us
eu:dentarg: eu
eu:wildhammer: eu
cn:stonemaul: cn
eu:blackhand: eu
eu:vashj: eu
us:arygos: us
us:runetotem: us
us:shadowsong: us
cn:neltharion: cn
eu:mug'thol: eu
cn:force of elemental: cn
eu:uldum: eu
eu:vek'lor: eu
us:ner'zhul: us
kr:ragnaros: kr
tw:quel'dorei: tw
cn:doomwalker: cn
"tw:kel\xE2\x80\x99thuzad": tw
eu:baelgun: eu
us:kargath: us
us:ysondre: us
eu:arthas: eu
kr:kul tiras: kr
cn:soulflayer: cn
eu:uldaman: eu
eu:jaedenar: eu
cn:onyxia: cn
us:firetree: us
cn:scarlet crusade: cn
cn:outland: cn
tw:sundown marsh: tw
us:anetheron: us
us:uther: us
tw:black dragonflight: tw
cn:world tree: cn
eu:medivh: eu
us:the underbog: us
eu:wrathbringer: eu
cn:moonglade: cn
eu:argent dawn: eu
eu:thunderhorn: eu
cn:icecrown: cn
us:shu'halo: us
cn:gazlowe: cn
cn:frostwolf: cn
cn:hakkar: cn
us:undermine: us
cn:shattered halls: cn
cn:dalvengyr: cn
kr:medivh: kr
cn:rangers: cn
eu:der rat von dalaran: eu
us:khaz'goroth: us
eu:xavius: eu
us:kirin tor: us
us:proudmoore: us
kr:uther: kr
cn:karazhan: cn
eu:antonidas: eu
cn:argus: cn
cn:dimensius: cn
cn:dark portal: cn
us:misha: us
us:garona: us
us:haomarush: us
eu:crushridge: eu
cn:balnazzar: cn
cn:direwing: cn
cn:sen'jin: cn
eu:exodar: eu
us:emerald dream: us
eu:madmortem: eu
us:stormrage: us
eu:tichondrius: eu
cn:aggramar: cn
eu:executus: eu
cn:emeriss: cn
cn:storm eye: cn
eu:onyxia: eu
us:azgalor: us
cn:runetotem: cn
cn:greymane: cn
eu:ravenholdt: eu
kr:zul'jin: kr
cn:emerald dream: cn
tw:balnazzar: tw
us:spinebreaker: us
us:azshara: us
cn:demonslayer: cn
cn:alleria: cn
cn:astalor: cn
us:daggerspine: us
us:mannoroth: us
us:shattered halls: us
eu:bladefist: eu
cn:chillwind point: cn
eu:silvermoon: eu
us:lethon: us
cn:scholomance: cn
cn:gruul: cn
eu:hyjal: eu
cn:smolderthorn: cn
cn:the steamvault: cn
cn:dar'khan: cn
cn:gold road: cn
cn:gorehowl: cn
kr:durotan: kr
eu:destromath: eu
cn:thoradin: cn
cn:windrunner: cn
cn:well of eternity: cn
eu:hakkar: eu
us:detheroc: us
us:the venture co: us
cn:explorer's league: cn
cn:anetheron: cn
cn:aviana: cn
eu:drak'thul: eu
cn:dunemaul: cn
us:wyrmrest accord: us
us:garithos: us
us:akama: us
us:shadowmoon: us
kr:malfurion: kr
"eu:\xD0\x93\xD1\x80\xD0\xBE\xD0\xBC": eu
us:aggramar: us
cn:flame crest: cn
us:ursin: us
us:elune: us
eu:the sha'tar: eu
eu:ahn'qiraj: eu
eu:lightning's blade: eu
eu:bloodhoof: eu
us:blackrock: us
us:greymane: us
us:gul'dan: us
us:drakkari: us
cn:hellscream: cn
eu:sanguino: eu
us:magtheridon: us
us:turalyon: us
eu:kul tiras: eu
cn:bronzebeard: cn
cn:cho'gall: cn
cn:archaedas: cn
cn:xavian: cn
eu:azuremyst: eu
"eu:festung der st\xC3\xBCrme": eu
us:blackhand: us
us:caelestrasz: us
eu:talnivarr: eu
eu:burning legion: eu
us:thorium brotherhood: us
us:skullcrusher: us
us:malygos: us
us:coilfang: us
eu:khadgar: eu
cn:hearthglen: cn
cn:sundown marsh: cn
us:auchindoun: us
cn:aerie peak: cn
us:dunemaul: us
cn:stormrage: cn
eu:ysondre: eu
eu:bronze dragonflight: eu
us:malorne: us
cn:thunder axe fortress: cn
us:doomhammer: us
us:staghelm: us
tw:whisperwind: tw
cn:immol'thar: cn
cn:eranikus: cn
us:korialstrasz: us
tw:light's hope: tw
eu:kargath: eu
cn:thunderaan: cn
cn:executus: cn
us:rexxar: us
"eu:\xD0\xA1\xD0\xB5\xD0\xB4\xD0\xBE\xD0\xB3\xD1\x80\xD0\xB8\xD0\xB2": eu
eu:alexstrasza: eu
cn:azshara: cn
us:quel'thalas: us
tw:strand of the ancients: tw
cn:cenarius: cn
cn:silverpine forest: cn
eu:shattered hand: eu
cn:mossflayer: cn
us:khaz modan: us
cn:whisperwind: cn
cn:mannoroth: cn
us:cho'gall: us
eu:drek'thar: eu
cn:anzu: cn
eu:zuluhed: eu
eu:azjol-nerub: eu
tw:warsong: tw
cn:draenor: cn
us:cenarion circle: us
kr:dalaran: kr
us:hydraxis: us
"eu:\xD0\x94\xD1\x80\xD0\xB0\xD0\xBA\xD0\xBE\xD0\xBD\xD0\xBE\xD0\xBC\xD0\xBE\xD1\x80": eu
"eu:la croisade \xC3\xA9carlate": eu
eu:minahonda: eu
eu:anachronos: eu
us:spirestone: us
eu:trollbane: eu
"eu:\xD0\xA2\xD0\xB5\xD1\x80\xD0\xBC\xD0\xBE\xD1\x88\xD1\x82\xD0\xB5\xD0\xBF\xD1\x81\xD0\xB5\xD0\xBB\xD1\x8C": eu
kr:norgannon: kr
eu:echsenkessel: eu
cn:altar of storms: cn
eu:frostwhisper: eu
eu:darkspear: eu
cn:blackrock: cn
cn:itharius: cn
us:argent dawn: us
cn:ironaya: cn
us:antonidas: us
eu:tirion: eu
eu:hellfire: eu
cn:vaelastrasz: cn
cn:bloodmaul: cn
eu:blutkessel: eu
eu:blade's edge: eu
eu:nera'thor: eu
eu:sunstrider: eu
"eu:\xD0\xA2\xD0\xBA\xD0\xB0\xD1\x87 \xD0\xA1\xD0\xBC\xD0\xB5\xD1\x80\xD1\x82\xD0\xB8": eu
cn:jaedenar: cn
cn:blackhand: cn
"eu:\xD0\x92\xD0\xB5\xD1\x87\xD0\xBD\xD0\xB0\xD1\x8F \xD0\x9F\xD0\xB5\xD1\x81\xD0\xBD\xD1\x8F": eu
eu:nathrezim: eu
cn:tortheldrin: cn
kr:tirion: kr
cn:bronze dragonflight: cn
cn:illidan: cn
cn:thunderhorn: cn
cn:brutallus: cn
cn:fenris: cn
eu:bloodfeather: eu
cn:malygos: cn
cn:death's door: cn
cn:andorhal: cn
us:suramar: us
eu:bloodscalp: eu
cn:grim batol: cn
us:moon guard: us
cn:doomhammer: cn
cn:lothar: cn
eu:malfurion: eu
eu:naxxramas: eu
eu:krag'jin: eu
us:bladefist: us
us:tichondrius: us
cn:danath trollbane: cn
cn:vek'lor: cn
us:terenas: us
tw:spirestone: tw
cn:silver hand: cn
us:bonechewer: us
us:altar of storms: us
eu:nethersturm: eu
cn:khardros: cn
eu:alonsus: eu
cn:ashbringer: cn
eu:bronzebeard: eu
cn:laughing skull: cn
cn:splinter fist: cn
us:barthilas: us
cn:deephome: cn
cn:proudmoore: cn
us:drak'thul: us
us:eredar: us
eu:arena tournament 1: eu
us:smolderthorn: us
us:sisters of elune: us
cn:winterspring: cn
eu:arena tournament 2: eu
eu:boulderfist: eu
cn:deepfury: cn
cn:al'akir: cn
cn:golemagg: cn
cn:searinox: cn
us:andorhal: us
eu:arena tournament 3: eu
us:bloodhoof: us
eu:shattered halls: eu
kr:elune: kr
tw:frenzyheart: tw
eu:rashgarroth: eu
cn:frostwhisper: cn
cn:kil'jaeden: cn
us:ravencrest: us
eu:arena tournament 4: eu
us:garrosh: us
eu:ysera: eu
us:kul tiras: us
eu:arena tournament 5: eu
us:bleeding hollow: us
eu:gorgonnash: eu
us:darrowmere: us
eu:arena tournament 6: eu
eu:blackmoore: eu
us:azuremyst: us
cn:aszune: cn
eu:les sentinelles: eu
cn:blood furnace: cn
eu:ragnaros: eu
"eu:\xD0\xA0\xD0\xB5\xD0\xB2\xD1\x83\xD1\x89\xD0\xB8\xD0\xB9 \xD1\x84\xD1\x8C\xD0\xBE\xD1\x80\xD0\xB4": eu
eu:warsong: eu
us:crushridge: us
tw:storm peaks: tw
tw:sartharion: tw
eu:die ewige wacht: eu
eu:zul'jin: eu
cn:bloodfeather: cn
eu:lothar: eu
cn:shadowfang keep: cn
us:tanaris: us
us:burning legion: us
us:kilrogg: us
us:gundrak: us
us:silvermoon: us
eu:norgannon: eu
eu:sargeras: eu
cn:shadowmoon: cn
cn:fist of the titans: cn
"eu:\xD0\x9A\xD0\xBE\xD1\x80\xD0\xBE\xD0\xBB\xD1\x8C-\xD0\xBB\xD0\xB8\xD1\x87": eu
cn:lushwater oasis: cn
eu:zirkel des cenarius: eu
cn:lord kazzak: cn
cn:bladefist: cn
us:rivendare: us
us:gnomeregan: us
us:shattered hand: us
kr:azshara: kr
cn:magatha: cn
eu:arak-arahm: eu
eu:ghostlands: eu
tw:aeonus: tw
cn:alterac mountains: cn
cn:rhonin: cn
cn:barthilas: cn
kr:alexstrasza: kr
cn:lightning's blade: cn
us:trollbane: us
cn:que'danas: cn
cn:jin'do: cn
cn:taerar: cn
eu:dragonmaw: eu
us:scilla: us
cn:alexstrasza: cn
eu:dragonblight: eu
eu:aszune: eu
eu:eitrigg: eu
cn:gyth: cn
"eu:mar\xC3\xA9cage de zangar": eu
cn:windshear crag: cn
cn:ahn'qiraj: cn
cn:azuregos: cn
us:darkspear: us
us:anvilmar: us
eu:nagrand: eu
cn:darrowmere: cn
us:echo isles: us
cn:hectae: cn
us:terokkar: us
cn:azjol-nerub: cn
kr:gul'dan: kr
eu:coliseum 2: eu
cn:kul tiras: cn
us:thrall: us
us:nazjatar: us
eu:kazzak: eu
us:duskwood: us
kr:kargath: kr
us:kalecgos: us
cn:arathor: cn
us:nathrezim: us
us:llane: us
eu:frostmane: eu
us:gilneas: us
us:shadow council: us
tw:gnomeregan: tw
cn:lich king: cn
cn:ragnaros: cn
cn:tanaris: cn
cn:shadow council: cn
eu:kael'thas: eu
cn:kurdran: cn
us:malfurion: us
eu:die todeskrallen: eu
cn:barrens: cn
tw:arthas: tw
cn:holy chanter: cn
cn:tyrande: cn
eu:outland: eu
cn:arygos: cn
cn:dream bough: cn
us:draka: us
cn:aessina: cn
cn:gnomeregan: cn
cn:sylvanas: cn
us:draenor: us
eu:un'goro: eu
us:dark iron: us
cn:sargeras: cn
eu:taerar: eu
cn:nefarian: cn
cn:rivendare: cn
cn:alythess: cn
us:stormscale: us
cn:archimonde: cn
us:aegwynn: us
cn:hogger: cn
cn:dragonblight: cn
us:bronzebeard: us
eu:grim batol: eu
us:thaurissan: us
cn:arathi: cn
eu:frostwolf: eu
cn:mograine: cn
eu:die arguswacht: eu
cn:rend: cn
us:alleria: us
eu:garrosh: eu
cn:dustwind gulch: cn
cn:bone wastes: cn
us:black dragonflight: us
us:skywall: us
eu:scarshield legion: eu
us:jubei'thos: us
cn:burning blade: cn
eu:hellscream: eu
cn:darkspear: cn
eu:sen'jin: eu
us:illidan: us
eu:ulduar: eu
cn:boulderfist: cn
us:dethecus: us
kr:eye of the storm: kr
us:shandris: us
us:bloodscalp: us
tw:wrathbringer: tw
kr:arena tournament 1: kr
cn:uldum: cn
eu:mal'ganis: eu
kr:arena tournament 2: kr
cn:the mechanar: cn
cn:legion hold: cn
cn:fray island: cn
kr:arena tournament 3: kr
eu:aerie peak: eu
cn:sethekk: cn
"eu:\xD0\x93\xD0\xB0\xD0\xBB\xD0\xB0\xD0\xBA\xD1\x80\xD0\xBE\xD0\xBD\xD0\xB4": eu
cn:whispering shore: cn
us:whisperwind: us
us:norgannon: us
eu:todeswache: eu
cn:black dragonflight: cn
eu:arygos: eu
eu:saurfang: eu
us:area 52: us
tw:stormscale: tw
eu:das konsortium: eu
us:durotan: us
us:vek'nilash: us
eu:eldre'thalas: eu
cn:stratholme: cn
eu:darkmoon faire: eu
eu:lightbringer: eu
us:mok'nathal: us
cn:malfurion: cn
cn:naxxramas: cn
us:drenden: us
cn:ravencrest: cn
cn:garona: cn
cn:temple of elune: cn
kr:deathwing: kr
cn:bloodhoof: cn
cn:grimtotem: cn
eu:conseil des ombres: eu
eu:ner'zhul: eu
cn:rajaxx: cn
cn:jammal'an: cn
eu:arathi: eu
cn:dark phantom: cn
us:steamwheedle cartel: us
tw:wintergrasp: tw
us:dragonmaw: us
cn:the forgotten coast: cn
cn:lethon: cn
eu:emerald dream: eu
eu:shadowsong: eu
cn:ossirian: cn
us:gorgonnash: us
cn:maulgar: cn
cn:liadrin: cn
us:blackwing lair: us
cn:mug'thol: cn
us:drak'tharon: us
cn:sapphiron: cn
us:icecrown: us
eu:dun morogh: eu
eu:lordaeron: eu
us:tortheldrin: us
eu:shen'dralar: eu
cn:skywall: cn
cn:prestor: cn
eu:nozdormu: eu
us:frostmane: us
us:wildhammer: us
cn:feathermoon: cn
cn:poison-tipped bone spear: cn
cn:thousand needles: cn
eu:gilneas: eu
kr:llane: kr
"eu:\xD0\x91\xD0\xBE\xD1\x80\xD0\xB5\xD0\xB9\xD1\x81\xD0\xBA\xD0\xB0\xD1\x8F \xD1\x82\xD1\x83\xD0\xBD\xD0\xB4\xD1\x80\xD0\xB0": eu
eu:mazrigos: eu
cn:abbendis: cn
kr:hyjal: kr
cn:modgud: cn
cn:zul'jin: cn
cn:deatholme: cn
cn:garr: cn
cn:stromgarde keep: cn
kr:wildhammer: kr
us:kael'thas: us
us:silver hand: us
cn:magmadar: cn
cn:entropius: cn
cn:c'thun: cn
eu:garona: eu
cn:echo ridge: cn
eu:azshara: eu
eu:varimathras: eu
cn:eldre'thalas: cn
"eu:\xD0\xAF\xD1\x81\xD0\xB5\xD0\xBD\xD0\xB5\xD0\xB2\xD1\x8B\xD0\xB9 \xD0\xBB\xD0\xB5\xD1\x81": eu
us:gorefiend: us
eu:sporeggar: eu
cn:vek'nilash: cn
eu:rajaxx: eu
eu:doomhammer: eu
eu:auchindoun: eu
eu:the maelstrom: eu
cn:durotan: cn
us:mug'thol: us
kr:garona: kr
cn:hyjal: cn
cn:nekros: cn
us:alterac mountains: us
us:chromaggus: us
us:dalaran: us
eu:draenor: eu
cn:ring of trials: cn
cn:eonar: cn
eu:aegwynn: eu
us:grizzly hills: us
cn:gadgetzan: cn
us:galakrond: us
cn:pandaren: cn
eu:earthen ring: eu
us:frostwolf: us
us:jaedenar: us
eu:emeriss: eu
"eu:\xD0\x93\xD0\xBE\xD1\x80\xD0\xB4\xD1\x83\xD0\xBD\xD0\xBD\xD0\xB8": eu
"eu:\xD0\xA0\xD0\xB0\xD0\xB7\xD1\x83\xD0\xB2\xD0\xB8\xD0\xB9": eu
eu:proudmoore: eu
cn:rexxar: cn
us:blood furnace: us
tw:onyxia: tw
us:arthas: us
cn:ner'zhul: cn
eu:gul'dan: eu
eu:nordrassil: eu
cn:dustbelcher: cn
cn:booty bay: cn
eu:alleria: eu
cn:dragonmaw: cn
eu:kil'jaeden: eu
eu:temple noir: eu
eu:dun modr: eu
cn:firetree: cn
us:dath'remar: us
us:dragonblight: us
eu:deathwing: eu
us:fizzcrank: us
us:uldaman: us
tw:altar of storms: tw
us:arathor: us
eu:aggramar: eu
cn:burning steppes: cn
us:mal'ganis: us
us:medivh: us
cn:frostmane: cn
cn:galardell: cn
eu:malygos: eu
us:ravenholdt: us
us:khadgar: us
cn:northrend: cn
eu:turalyon: eu
eu:terrordar: eu
cn:burning legion: cn
cn:dark iron: cn
cn:deathforge: cn
cn:valley of kings: cn
cn:stranglethorn: cn
tw:frostmane: tw
cn:kael'thas: cn
tw:world tree: tw
eu:theradras: eu
"eu:\xD0\xA1\xD1\x82\xD1\x80\xD0\xB0\xD0\xB6 \xD0\xA1\xD0\xBC\xD0\xB5\xD1\x80\xD1\x82\xD0\xB8": eu
eu:zenedar: eu
eu:khaz'goroth: eu
"eu:\xD0\xA1\xD0\xB2\xD0\xB5\xD0\xB6\xD0\xB5\xD0\xB2\xD0\xB0\xD1\x82\xD0\xB5\xD0\xBB\xD1\x8C \xD0\x94\xD1\x83\xD1\x88": eu
cn:gorefiend: cn
us:kel'thuzad: us
us:destromath: us
cn:the botanica: cn
tw:nesingwary: tw
us:executus: us
tw:demon soul: tw
us:exodar: us
tw:bleeding hollow: tw
eu:agamaggan: eu
us:cairne: us
eu:shadowmoon: eu
cn:vilebranch: cn
us:windrunner: us
eu:dunemaul: eu
us:thunderhorn: us
us:alexstrasza: us
eu:arena pass 1: eu
us:cenarius: us
tw:coliseum 1: tw
cn:chromaggus: cn
us:borean tundra: us
eu:colinas pardas: eu
us:onyxia: us
cn:shattered hand: cn
tw:nightsong: tw
kr:windrunner: kr
cn:frostmourne: cn
cn:dentarg: cn
us:azjol-nerub: us
tw:dreadmist peak: tw
cn:fel rock: cn
eu:throk'feroth: eu
tw:quel'danas: tw
eu:cho'gall: eu
us:twisting nether: us
tw:demon fall canyon: tw
cn:cassandra: cn
us:nazgrel: us
cn:geddon: cn
cn:firegut: cn
us:hellscream: us
eu:der mithrilorden: eu
"eu:\xD0\x9F\xD0\xB8\xD1\x80\xD0\xB0\xD1\x82\xD1\x81\xD0\xBA\xD0\xB0\xD1\x8F \xD0\xB1\xD1\x83\xD1\x85\xD1\x82\xD0\xB0": eu
cn:baelgun: cn
cn:fire plume ridge: cn
kr:alleria: kr
cn:eredar: cn
cn:firelands: cn
us:lightning's blade: us
us:hakkar: us
cn:uldaman: cn
kr:hellscream: kr
